# backend/Dockerfile
FROM python:3.11-slim

WORKDIR /app

# system deps for psycopg2 (if using psycopg2-binary you can remove these)
RUN apt-get update && apt-get install -y build-essential libpq-dev gcc && rm -rf /var/lib/apt/lists/*

COPY ./app /app

# Install deps
COPY ./app/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
